#!/usr/bin/python3
 
# Calculate system metrics such as
# load, memory, and storage.
 
# Import modules.
import os
import sys
 
 
# Only allow root user to execute the script.
if os.geteuid()==0:
  print('Allowed to execute.')
else:
  print('Access denied. Execute as Sudoer.')
 
# Get 1 min, 5 min, and 15 min
# system load average.
# Defining function.
def get_system_load():
  print('Calculating system load...')
  print('Enter time range for system load (1,5,15):')
  time_range = int(input())
  if time_range==1:
    output = os.getloadavg()[0]
  elif time_range==5:
    output = os.getloadavg()[1]
  elif time_range==15:
    output = os.getloadavg()[2]
  else:
    print('Invalid input.')
  print('The system load average for %i minute is %s' %(time_range,output))
 
# Get free, used, and available
# system memory.
def get_system_memory():
  print('Calculating system memory...')
 
# Get free, used, and available
# system storage.
def get_system_storage():
  print('Calculating system storage...')
 
 
# Calling function.
# get_system_load()
 
# Calling functions based on CLI arguments.
if sys.argv[1]=='load':
  get_system_load()
elif sys.argv[1]=='memory':
  get_system_memory()
elif sys.argv[1]=='storage':
  get_system_storage()
else:
  print('Help: ./system-metric.py {load|memory|storage}')
